name: weeklyreport

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 6'

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install dependencies
        run: pip install requests

      - name: run
        run: python -u weeklyreport.py
        env:
          OPEN_CLOUD_API_KEY: ${{ secrets.OPEN_CLOUD_API_KEY }}
          ID: ${{ secrets.TEST_ID }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
